# -*- coding: utf-8 -*-
"""31498499_Hw9Problem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmIeG82rADhD32GnUfOs6nPtlzOlibGm
"""

import requests
from bs4 import BeautifulSoup
from pymongo import MongoClient
import time

def main():
    client = MongoClient()
    db = client['finData']
    collection = db['actData']

    while True:
        d = scrape_data()
        if d:
            print("Updating database with latest stock information...")
            collection.insert_many(d)
        time.sleep(180)

def scrape_data():
    url = "https://finance.yahoo.com/most-active"
    headers = {'User-Agent': 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)'}
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
    except requests.RequestException as error:
        print(f"Error retrieving stock data: {error}")
        return None

    return parse_data(response.text)

def parse_data(html):
    soup = BeautifulSoup(html, 'html.parser')
    t = soup.find('table', attrs={'class': 'W(100%)'})
    r = t.find_all('tr')[1:]

    stock_list = []
    for row in r:
        cols = row.find_all('td')
        stock = {
            'Symbol': cols[0].text.strip(),
            'Name': cols[1].text.strip(),
            'Price': cols[2].text.strip(),
            'Change': cols[3].text.strip(),
            'Volume': cols[6].text.strip()
        }
        stock_list.append(stock)
    return stock_list

if __name__ == "__main__":
    main()